[E 240927 19:42:23 smartConnect:221] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/auth/angelbroking/user/v1/loginByPassword. Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': '16:3e:df:f4:c9:b5', 'Accept': 'application/json', 'X-PrivateKey': 'BGjV4pis', 'X-UserType': 'USER', 'X-SourceID': 'WEB', 'Authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6IkFBQUEwNTQ0MzkiLCJyb2xlcyI6MCwidXNlcnR5cGUiOiJVU0VSIiwidG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlYM1I1Y0dVaU9pSmpiR2xsYm5RaUxDSjBiMnRsYmw5MGVYQmxJam9pZEhKaFpHVmZZV05qWlhOelgzUnZhMlZ1SWl3aVoyMWZhV1FpT2pZc0luTnZkWEpqWlNJNklqTWlMQ0prWlhacFkyVmZhV1FpT2lJeFlUbGxOR05tTUMwMU5qVTFMVE5tWW1ZdE9XUTFZeTFtT1RFeU0yUXpObVl6TWpNaUxDSnJhV1FpT2lKMGNtRmtaVjlyWlhsZmRqRWlMQ0p2Ylc1bGJXRnVZV2RsY21sa0lqbzJMQ0p3Y205a2RXTjBjeUk2ZXlKa1pXMWhkQ0k2ZXlKemRHRjBkWE1pT2lKaFkzUnBkbVVpZlgwc0ltbHpjeUk2SW5SeVlXUmxYMnh2WjJsdVgzTmxjblpwWTJVaUxDSnpkV0lpT2lKQlFVRkJNRFUwTkRNNUlpd2laWGh3SWpveE56STNOVFU0TnpBMUxDSnVZbVlpT2pFM01qYzBOalEyTnpNc0ltbGhkQ0k2TVRjeU56UTJORFkzTXl3aWFuUnBJam9pWldFMlpqSTNOVE10WW1Fd1lTMDBPRFZoTFdKak5URXROREEzTVdNMk5ERXlZV0ZoSW4wLmZ2cnh2TWNmd1FSOW5XcDg0T0EzakJmOU1CV1RWU3lwbUpHaUZnRWRmYnNkZnpMbzZxYVNUZTFIakQ1aVlaQkFtMjFxSTNuWEZLSFkwV2xYaHFPX3ZSdV9rVHo5UDVjR3l1NkFRQV96NjBvZkRLaFo1MTRSOE13TkMtTE12NS0zNk5kTTJRZ0FOMV80UjV0UTlHYWdLN3BPbG1iZG1QVllQVDlZTl95T2lPbyIsIkFQSS1LRVkiOiJCR2pWNHBpcyIsImlhdCI6MTcyNzQ2NDczMywiZXhwIjoxNzI3NTU4NzA1fQ.EsgjNs7EvMulXpLdiGzTNnXELk91Jz91wn8m6SjwLe-WKLSdrxNIjO-tYJhf_3q5QWMUZ04A0Y8fd9to3lyHXg'}, Request: {'clientcode': 'AAAA054439', 'password': '1494', 'totp': '322748'}, Response: HTTPSConnectionPool(host='apiconnect.angelone.in', port=443): Max retries exceeded with url: /rest/auth/angelbroking/user/v1/loginByPassword (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x130824400>: Failed to resolve 'apiconnect.angelone.in' ([Errno 8] nodename nor servname provided, or not known)"))
